rnn:
  rules : [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT, AntiPerceptualDecisionMakingDelayResponseT]
  parameters:
    architecture: 
      - LeakyRNN
      # - LeakyGRU
      # - LSTM
    activations:
      # - relu
      - softplus
      - tanh
    freeze:
      - True 
      - False
    nopretrain:
      - True
      - False
    n_rnn:
      - 128
      - 256
    learning_rate:
      - 0.0001
      - 0.001
  pretrain:
    ruleset: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
    # ruleset: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT]
    T: 1000
    batch: 64
    num_epochs: 50
  train:
    ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
    # ruleset: [AntiGoNogoDelayResponseT]
    T: 1000
    batch: 64
    num_epochs: 20
analysis:
  epochs: [stim1]
  rule: [delayanti]
  trimming_method: time_average
  model: models/model.pth
# dsa:
#   n_delays: 50
#   delay_interval: 20
#   rank: 50
#   device: cuda
dsa:
  n_delays: 20
  delay_interval: 1
  rank: 20
  device: cuda
simulations:
  dt: 0.02 # 20 ms
  num_steps: 200
  num_samples: 200
  lorenz_parameters: {
      'one_attractor': [{'s': 10, 'r': 0.25, 'b': 2.667},{'s': 10, 'r': 0.5, 'b': 2.667},{'s': 10, 'r': 0.75, 'b': 2.667}],
      'two_stable_attractors': [{'s': 10, 'r': 5, 'b': 2.667},{'s': 10, 'r': 10, 'b': 2.667},{'s': 10, 'r': 15, 'b': 2.667}],
      'two_unstable_attractors': [{'s': 10, 'r': 30, 'b': 2.667},{'s': 10, 'r': 40, 'b': 2.667},{'s': 10, 'r': 50, 'b': 2.667}]
      }
  perturbations: 
    model1: 
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125
    model2:
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125
    model3: 
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125  
  sigma: 1
  order: [0,1,2,3]