rnn:
  parameters:
    rnn_type: 
      - leaky_rnn
      - leaky_gru
    activations:
      - leaky_relu
      - relu
      - softplus
      - tanh
    n_rnn:
      - 128
      - 256
    learning_rate:
      - 0.01
      - 0.001
    batch_size_train:
      - 64
      - 128
    freeze:
      - True
      - False
    nopretrain:
      - True
      - False
mamba:
  parameters:
    d_model:
      - 8
      - 16
    n_layers:
      - 1
      - 2
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
    batch_size_train:
      - 16
      - 32
      - 64
      - 128
    
PDM:
  all_rules: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT, AntiPerceptualDecisionMakingDelayResponseT]
  rules_analysis: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT, AntiPerceptualDecisionMakingDelayResponseT]
  groups:
    master:
      pretrain:
        ruleset: []
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: False
    pretrain_frozen:
      pretrain: 
        ruleset: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    pretrain_unfrozen:
      pretrain: 
        ruleset: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: False
    pretrain_basic_frozen:
      pretrain:
        ruleset: [PerceptualDecisionMakingT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    pretrain_anti_frozen:
      pretrain:
        ruleset: [AntiPerceptualDecisionMakingT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    pretrain_delay_frozen:
      pretrain:
        ruleset: [PerceptualDecisionMakingDelayResponseT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    pretrain_basic_anti_frozen:
      pretrain:
        ruleset: [PerceptualDecisionMakingT, AntiPerceptualDecisionMakingT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    pretrain_basic_delay_frozen:
      pretrain:
        ruleset: [PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    master_frozen:
      pretrain:
        ruleset: []
      train:
        ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
        frozen: True
    untrained:
      pretrain:
        ruleset: []
      train:
        ruleset: []
        frozen: True
GoNogo: 
  all_rules: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT, AntiGoNogoDelayResponseT]
  rules_analysis: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT, AntiGoNogoDelayResponseT]
  groups:
    master:
      pretrain:
        ruleset: []
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: False
    pretrain_frozen:
      pretrain:
        ruleset: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    pretrain_unfrozen:
      pretrain:
        ruleset: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: False
    pretrain_basic_frozen:
      pretrain:
        ruleset: [GoNogoT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    pretrain_anti_frozen:
      pretrain:
        ruleset: [AntiGoNogoT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    pretrain_delay_frozen:
      pretrain:
        ruleset: [GoNogoDelayResponseT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    pretrain_basic_anti_frozen:
      pretrain:
        ruleset: [GoNogoT, AntiGoNogoT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    pretrain_basic_delay_frozen:
      pretrain:
        ruleset: [GoNogoT, GoNogoDelayResponseT]
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    master_frozen:
      pretrain:
        ruleset: []
      train:
        ruleset: [AntiGoNogoDelayResponseT]
        frozen: True
    untrained:
      pretrain:
        ruleset: []
      train:
        ruleset: []
        frozen: True
dsa:
  n_delays: 33
  delay_interval: 6
  rank: 100
  device: cuda
simulations:
  dt: 0.01 # 20 ms
  num_steps: 200
  num_samples: 200
  lorenz_parameters: {
      'one_attractor': [{'s': 10, 'r': 0.25, 'b': 2.667},{'s': 10, 'r': 0.5, 'b': 2.667},{'s': 10, 'r': 0.75, 'b': 2.667}],
      'two_stable_attractors': [{'s': 10, 'r': 5, 'b': 2.667},{'s': 10, 'r': 10, 'b': 2.667},{'s': 10, 'r': 15, 'b': 2.667}],
      'two_unstable_attractors': [{'s': 10, 'r': 30, 'b': 2.667},{'s': 10, 'r': 40, 'b': 2.667},{'s': 10, 'r': 50, 'b': 2.667}]
      }
  perturbations: 
    model1: 
      epoch1: 0.01
      epoch2: 0.005
      epoch3: 0.0025
    model2:
      epoch1: 0.01
      epoch2: 0.005
      epoch3: 0.0025
    model3: 
      epoch1: 0.01
      epoch2: 0.005
      epoch3: 0.0025
  sigma: 1
  order: [0,1,2,3]