all_rules: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT, AntiPerceptualDecisionMakingDelayResponseT] #[GoNogoT, AntiGoNogoT, GoNogoDelayResponseT, AntiGoNogoDelayResponseT]
rules_analysis: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT, AntiPerceptualDecisionMakingDelayResponseT]
rnn:
  parameters:
    rnn_type: 
      - leaky_rnn
      - leaky_gru
    activations:
      - leaky_relu
      - relu
      - softplus
      - tanh
    n_rnn:
      - 128
      - 256
    learning_rate:
      - 0.0001
      - 0.001
    batch_size_train:
      - 128
      - 256
    freeze:
      - True
      - False
    nopretrain:
      - True
      - False
groups:
  master:
    pretrain:
      ruleset: []
    train:
      ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
      frozen: False
  pretrain_frozen:
    pretrain: 
      ruleset: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
    train:
      ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
      frozen: True
  pretrain_unfrozen:
    pretrain: 
      ruleset: [AntiPerceptualDecisionMakingT, PerceptualDecisionMakingT, PerceptualDecisionMakingDelayResponseT]
    train:
      ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
      frozen: False
  delay: 
    pretrain:
      ruleset: []
    train:
      ruleset: [PerceptualDecisionMakingDelayResponseT]
      frozen: False
  anti:
    pretrain:
      ruleset: []
    train:
      ruleset: [AntiPerceptualDecisionMakingT]
      frozen: False
  basic:
    pretrain:
      ruleset: []
    train:
      ruleset: [PerceptualDecisionMakingT]
      frozen: False
  untrained:
    pretrain:
      ruleset: []
    train:
      ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
      frozen: True
  # pretrained_PDM_APDM:
  #   pretrain:
  #     ruleset: [PerceptualDecisionMakingT, AntiPerceptualDecisionMakingT]
  #   train:
  #     ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
  #     frozen: True
  # pretrained_APDM_DPDM:
  #   pretrain:
  #     ruleset: [AntiPerceptualDecisionMakingT,PerceptualDecisionMakingDelayResponseT]
  #   train:
  #     ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
  #     frozen: True
  # pretrained_PDM_DPDM:
  #   pretrain:
  #     ruleset: [PerceptualDecisionMakingT,PerceptualDecisionMakingDelayResponseT]
  #   train:
  #     ruleset: [AntiPerceptualDecisionMakingDelayResponseT]
  #     frozen: True
  # master-gonogo:
  #   pretrain:
  #     ruleset: []
  #   train:
  #     ruleset: [AntiGoNogoDelayResponseT]
  #     frozen: False
  # pretrain_frozen-gonogo:
  #   pretrain:
  #     ruleset: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT]
  #   train:
  #     ruleset: [AntiGoNogoDelayResponseT]
  #     frozen: True
  # pretrain_unfrozen-gonogo:
  #   pretrain:
  #     ruleset: [GoNogoT, AntiGoNogoT, GoNogoDelayResponseT]
  #   train:
  #     ruleset: [AntiGoNogoDelayResponseT]
  #     frozen: False
  # delay-gonogo:
  #   pretrain:
  #     ruleset: []
  #   train:
  #     ruleset: [GoNogoDelayResponseT]
  #     frozen: False
  # anti-gonogo:
  #   pretrain:
  #     ruleset: []
  #   train:
  #     ruleset: [AntiGoNogoT]
  #     frozen: False
  # basic-gonogo:
  #   pretrain:
  #     ruleset: []
  #   train:
  #     ruleset: [GoNogoT]
  #     frozen: False
  # untrained-gonogo:
  #   pretrain:
  #     ruleset: []
  #   train:
  #     ruleset: [AntiGoNogoDelayResponseT]
  #     frozen: True
analysis:
  epochs: [stim1]
  rule: [delayanti]
  trimming_method: time_average
  model: models/model.pth
dsa:
  n_delays: 20
  delay_interval: 10
  rank: 50
  device: cuda
simulations:
  dt: 0.01 # 20 ms
  num_steps: 200
  num_samples: 200
  lorenz_parameters: {
      'one_attractor': [{'s': 10, 'r': 0.25, 'b': 2.667},{'s': 10, 'r': 0.5, 'b': 2.667},{'s': 10, 'r': 0.75, 'b': 2.667}],
      'two_stable_attractors': [{'s': 10, 'r': 5, 'b': 2.667},{'s': 10, 'r': 10, 'b': 2.667},{'s': 10, 'r': 15, 'b': 2.667}],
      'two_unstable_attractors': [{'s': 10, 'r': 30, 'b': 2.667},{'s': 10, 'r': 40, 'b': 2.667},{'s': 10, 'r': 50, 'b': 2.667}]
      }
  perturbations: 
    model1: 
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125
    model2:
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125
    model3: 
      epoch1: 0.005
      epoch2: 0.0025
      epoch3: 0.00125  
  sigma: 1
  order: [0,1,2,3]