name: repal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - git+https://github.com/mitchellostrow/DSA.git#egg=dsa
    - git+https://github.com/nacloos/similarity-repository.git#egg=similarity-repository
    - git+https://github.com/alxndrTL/mamba.py.git@5cae1b2#egg=mambapy
    - six==1.16.0
    - matplotlib==3.8.3
    - pandas==2.2.1
    - pyyaml==6.0.1
    - ipdb==0.13.13
    - seaborn==0.13.2
    - jupyterlab==4.1.5
    - ipykernel==6.29.3
    - plotly==5.20.0
    - rsatoolbox==0.1.5
    - pytorch-lightning==2.2.2
    - neurogym==0.0.2
    - bokeh==3.4.2
