from neurogym.envs.perceptualdecisionmaking import PerceptualDecisionMaking
from neurogym.envs.perceptualdecisionmaking import PerceptualDecisionMakingDelayResponse
from main.task import AntiPerceptualDecisionMaking, AntiPerceptualDecisionMakingDelayResponse

tasks = ['AntiPerceptualDecisionMaking', 'PerceptualDecisionMaking', 'PerceptualDecisionMakingDelayResponse', 'AntiPerceptualDecisionMakingDelayResponse']